networks:
  main:

volumes:
  data-solr:

services:
  solr:
    container_name: "solr"
    image: "solr:9.8"
    ports:
      - "8983:8983"
    expose:
      - "8983"
    volumes:
      - "data-solr:/var/solr"
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8983/solr" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      main:
        aliases:
          - solr
    command:
      - "solr-precreate"
      - "solr-geonames"

  nginx:
    container_name: "nginx"
    image: "nginx:stable"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - "./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      main:
        aliases:
          - nginx
    depends_on:
      solr:
        condition: service_healthy
